### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basileLeroy** [DanteBoute/SASS#1]
# Feedback

## Technical
One of the key features while using SCSS/SASS, is the nesting of your selectors (elements, class names, id's)
Make sure to nest those correctly in the future exercises.

Otherwise, well done with the result, good job finding the "!default" and using that to overwrite a value once their is a new one.

In your message boxes, you created a new selector "basic-style" but you could also just have used the "message" as your base styling.

```scss
  .message {
    border: 1px solid #ccc;
    padding: $myPadding;
    margin: 16px;
    color: $text-color;
    background-color:$background-color1;
  }
  
  .success {
    @extend .message;
    background-color: green;
  }
```

## GIT
Your commits are a bit lacking. Try to aim for nothing less than 8-10 commits a day when working on a project. 2 commits over 2 days is not enough!

Commit messages like "NEW" and "Make it work" are not clear messages to other team members or event to yourself in the future. Instead describe what your changes were, and in a structured way: "Add variables for text colors", "Create new partials file to store list of variables", ...

Have a look at [GIT - Best Practices](https://github.com/becodeorg/GNT-Verou-5/blob/main/1.The-Field/05.Git/best-practises.md)
